# Master controller configuration
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_6
    - joint_7