# Configuration for the ROS Control controllers
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  
  # Forgiving constraints for simulation
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.2
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 20

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_6
    - joint_7

  # Forgiving constraints for simulation
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.2
    joint_6: {trajectory: 0.1, goal: 0.1}
    joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 20