# Gains for the gazebo_ros_control plugin
gazebo_ros_control:
  pid_gains:
    joint_1: {p: 700.0, i: 10.0, d: 50.0}
    joint_2: {p: 700.0, i: 10.0, d: 50.0}
    joint_3: {p: 700.0, i: 10.0, d: 50.0}
    joint_4: {p: 500.0, i: 5.0,  d: 20.0}
    joint_5: {p: 300.0, i: 1.0,  d: 10.0}
    joint_6: {p: 100.0, i: 0.01, d: 10.0}
    joint_7: {p: 100.0, i: 0.01, d: 10.0}